name: Build & Publish to Registry

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push WebApp
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./src/WebApp
        file: ./src/WebApp/Dockerfile
        tags: whiteduck/sample-mvc:latest

    - name: Build and push API
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./src/FredApi
        file: ./src/WebApp/Dockerfile
        tags: whiteduck/sample-api:latest
