name: Build & Publish to Registry Test

on:
  push:
    branches:
      - update/new-net-version

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push WebApp
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./src/WebApp
          file: ./src/WebApp/Dockerfile
          build-args: LOGO=logo-fred.png
          tags: whiteduck/sample-mvc:fred

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./src/FredApi
          file: ./src/FredApi/Dockerfile
          tags: whiteduck/sample-api:latest
